//! Built-in/external symbol filter.

use types::Language;

/// Filters out known built-in names that shouldn't be resolved to project symbols.
pub struct BuiltinFilter;

/// Built-in sets per language.
const TS_JS_BUILTINS: &[&str] = &[
    "console",
    "JSON",
    "Math",
    "Array",
    "Object",
    "String",
    "Number",
    "Boolean",
    "Function",
    "Date",
    "RegExp",
    "Error",
    "Map",
    "Set",
    "Promise",
    "Symbol",
    "WeakMap",
    "WeakSet",
    "Proxy",
    "Reflect",
    "Intl",
    "BigInt",
    "undefined",
    "NaN",
    "Infinity",
    "parseInt",
    "parseFloat",
    "isNaN",
    "isFinite",
    "eval",
    "encodeURI",
    "decodeURI",
    "setTimeout",
    "setInterval",
    "clearTimeout",
    "clearInterval",
    "fetch",
    "Response",
    "Request",
    "Headers",
    "FormData",
    "URL",
    "URLSearchParams",
    "Blob",
    "File",
    "FileReader",
    "AbortController",
    "Buffer",
    "process",
    "global",
    "globalThis",
    "window",
    "document",
    "navigator",
    "location",
    "history",
    "localStorage",
    "sessionStorage",
    "alert",
    "confirm",
    "prompt",
    "atob",
    "btoa",
];

const PYTHON_BUILTINS: &[&str] = &[
    "print",
    "len",
    "type",
    "int",
    "float",
    "str",
    "bool",
    "list",
    "dict",
    "tuple",
    "set",
    "frozenset",
    "range",
    "enumerate",
    "zip",
    "map",
    "filter",
    "sorted",
    "reversed",
    "abs",
    "all",
    "any",
    "bin",
    "hex",
    "oct",
    "chr",
    "ord",
    "divmod",
    "pow",
    "round",
    "sum",
    "min",
    "max",
    "isinstance",
    "issubclass",
    "hasattr",
    "getattr",
    "setattr",
    "delattr",
    "callable",
    "iter",
    "next",
    "open",
    "input",
    "repr",
    "format",
    "dir",
    "vars",
    "globals",
    "locals",
    "id",
    "hash",
    "compile",
    "exec",
    "eval",
    "help",
    "object",
    "Exception",
    "ValueError",
    "TypeError",
    "KeyError",
    "IndexError",
    "AttributeError",
    "ImportError",
    "RuntimeError",
    "StopIteration",
    "OSError",
    "IOError",
    "super",
    "self",
    "cls",
    "None",
    "True",
    "False",
    "NotImplemented",
    "Ellipsis",
    "__name__",
    "__main__",
    "__init__",
    "__file__",
    "__doc__",
    "__builtins__",
    "__package__",
];

/// Java built-in names from java.lang (auto-imported) and commonly used types.
const JAVA_BUILTINS: &[&str] = &[
    // Keywords / literals
    "this",
    "super",
    "null",
    // java.lang
    "Object",
    "Class",
    "String",
    "StringBuilder",
    "StringBuffer",
    "Integer",
    "Long",
    "Double",
    "Float",
    "Boolean",
    "Byte",
    "Short",
    "Character",
    "Void",
    "Number",
    "Math",
    "StrictMath",
    "System",
    "Runtime",
    "Process",
    "ProcessBuilder",
    "Thread",
    "Runnable",
    "ThreadLocal",
    "Throwable",
    "Exception",
    "Error",
    "RuntimeException",
    "IllegalArgumentException",
    "IllegalStateException",
    "NullPointerException",
    "IndexOutOfBoundsException",
    "ArrayIndexOutOfBoundsException",
    "ClassCastException",
    "ArithmeticException",
    "NumberFormatException",
    "UnsupportedOperationException",
    "InterruptedException",
    "IOException",
    "FileNotFoundException",
    "ClassNotFoundException",
    "NoSuchMethodException",
    "NoSuchFieldException",
    "IllegalAccessException",
    "InstantiationException",
    "SecurityException",
    "StackOverflowError",
    "OutOfMemoryError",
    "Iterable",
    "Iterator",
    "Collection",
    "List",
    "Set",
    "Map",
    "ArrayList",
    "LinkedList",
    "HashMap",
    "HashSet",
    "TreeMap",
    "TreeSet",
    "LinkedHashMap",
    "LinkedHashSet",
    "Hashtable",
    "Vector",
    "Stack",
    "Collections",
    "Arrays",
    "Objects",
    "Optional",
    "OptionalInt",
    "Comparator",
    "Comparable",
    "AutoCloseable",
    "Override",
    "Deprecated",
    "SuppressWarnings",
    "FunctionalInterface",
    "StackTraceElement",
    "Enum",
    "Record",
    // java.io common
    "File",
    "InputStream",
    "OutputStream",
    "Reader",
    "Writer",
    "PrintStream",
    "PrintWriter",
    "BufferedReader",
    "BufferedWriter",
    "Serializable",
    "Closeable",
    "Flushable",
    // java.net common
    "URL",
    "URI",
    "Socket",
    "ServerSocket",
    "InetAddress",
    // java.util common
    "Date",
    "Calendar",
    "Scanner",
    "Random",
    "Properties",
    "Base64",
    "Timer",
    "TimerTask",
    // java.time common
    "LocalDate",
    "LocalTime",
    "LocalDateTime",
    "Instant",
    "Duration",
    "Period",
    "ZoneId",
    "ZonedDateTime",
    "DateTimeFormatter",
    "Clock",
    // java.util.function
    "Function",
    "Consumer",
    "Supplier",
    "Predicate",
    "BiFunction",
    "BiConsumer",
    "BiPredicate",
    "UnaryOperator",
    "BinaryOperator",
];

/// C standard library names (commonly used, never project-defined).
const C_BUILTINS: &[&str] = &[
    // Keywords / literals
    "NULL",
    // stdio.h
    "printf",
    "fprintf",
    "sprintf",
    "snprintf",
    "scanf",
    "fscanf",
    "sscanf",
    "fopen",
    "fclose",
    "freopen",
    "fread",
    "fwrite",
    "fflush",
    "fgets",
    "fputs",
    "puts",
    "gets",
    "getchar",
    "putchar",
    "feof",
    "ferror",
    "clearerr",
    "fseek",
    "ftell",
    "rewind",
    "remove",
    "rename",
    "tmpfile",
    "tmpnam",
    "EOF",
    "FILE",
    "stdin",
    "stdout",
    "stderr",
    "BUFSIZ",
    "SEEK_SET",
    "SEEK_CUR",
    "SEEK_END",
    // stdlib.h
    "malloc",
    "calloc",
    "realloc",
    "free",
    "exit",
    "abort",
    "atexit",
    "quick_exit",
    "at_quick_exit",
    "atoi",
    "atol",
    "atof",
    "strtol",
    "strtoul",
    "strtod",
    "strtof",
    "rand",
    "srand",
    "abs",
    "labs",
    "div",
    "ldiv",
    "qsort",
    "bsearch",
    "getenv",
    "system",
    "EXIT_SUCCESS",
    "EXIT_FAILURE",
    "RAND_MAX",
    // string.h
    "memcpy",
    "memmove",
    "memset",
    "memcmp",
    "memchr",
    "strcpy",
    "strncpy",
    "strcat",
    "strncat",
    "strcmp",
    "strncmp",
    "strchr",
    "strrchr",
    "strstr",
    "strlen",
    "strtok",
    "strdup",
    "strerror",
    "strdup",
    // stddef.h / stdint.h / stdbool.h
    "size_t",
    "ptrdiff_t",
    "intptr_t",
    "uintptr_t",
    "int8_t",
    "int16_t",
    "int32_t",
    "int64_t",
    "uint8_t",
    "uint16_t",
    "uint32_t",
    "uint64_t",
    "bool",
    "true",
    "false",
    // assert.h
    "assert",
    "static_assert",
    // errno.h
    "errno",
    "EINVAL",
    "ENOENT",
    "ENOMEM",
    "ERANGE",
    // ctype.h
    "isalpha",
    "isdigit",
    "isalnum",
    "isspace",
    "isupper",
    "islower",
    "toupper",
    "tolower",
    "isprint",
    "ispunct",
    "iscntrl",
    "isxdigit",
    // signal.h
    "signal",
    "raise",
    "SIGINT",
    "SIGTERM",
    "SIGKILL",
    "SIGSEGV",
    "SIGABRT",
    "SIGFPE",
    "SIGILL",
];

/// C++ built-in names (C stdlib + C++ stdlib common types/functions).
const CPP_BUILTINS: &[&str] = &[
    // Includes most C builtins
    "NULL",
    "printf",
    "fprintf",
    "sprintf",
    "scanf",
    "malloc",
    "calloc",
    "realloc",
    "free",
    "exit",
    "abort",
    "atoi",
    "atol",
    "atof",
    "memcpy",
    "memset",
    "memcmp",
    "memchr",
    "strcpy",
    "strncpy",
    "strcat",
    "strcmp",
    "strncmp",
    "strchr",
    "strstr",
    "strlen",
    "strdup",
    "strerror",
    "size_t",
    "ptrdiff_t",
    "intptr_t",
    "uintptr_t",
    "int8_t",
    "int16_t",
    "int32_t",
    "int64_t",
    "uint8_t",
    "uint16_t",
    "uint32_t",
    "uint64_t",
    "assert",
    "errno",
    // Keywords / literals
    "nullptr",
    "this",
    // iostream
    "cout",
    "cin",
    "cerr",
    "clog",
    "endl",
    "flush",
    "ws",
    "noskipws",
    "skipws",
    "std",
    // STL containers
    "vector",
    "string",
    "wstring",
    "u16string",
    "u32string",
    "list",
    "forward_list",
    "deque",
    "queue",
    "priority_queue",
    "stack",
    "map",
    "set",
    "multimap",
    "multiset",
    "unordered_map",
    "unordered_set",
    "unordered_multimap",
    "unordered_multiset",
    "array",
    "bitset",
    "span",
    "pair",
    "tuple",
    "optional",
    "variant",
    "any",
    // STL algorithms
    "sort",
    "stable_sort",
    "find",
    "find_if",
    "find_if_not",
    "copy",
    "copy_if",
    "copy_n",
    "copy_backward",
    "transform",
    "for_each",
    "remove",
    "remove_if",
    "unique",
    "reverse",
    "rotate",
    "shuffle",
    "sample",
    "count",
    "count_if",
    "min",
    "max",
    "minmax",
    "clamp",
    "min_element",
    "max_element",
    "minmax_element",
    "accumulate",
    "reduce",
    "inner_product",
    "binary_search",
    "lower_bound",
    "upper_bound",
    "equal_range",
    "merge",
    "inplace_merge",
    "includes",
    "swap",
    "iter_swap",
    "exchange",
    "make_heap",
    "push_heap",
    "pop_heap",
    "sort_heap",
    "is_sorted",
    "is_heap",
    "nth_element",
    "partition",
    "stable_partition",
    "iota",
    "fill",
    "generate",
    "distance",
    "advance",
    "next",
    "prev",
    // Smart pointers
    "unique_ptr",
    "shared_ptr",
    "weak_ptr",
    "make_unique",
    "make_shared",
    "unique_lock",
    "lock_guard",
    // Utility
    "move",
    "forward",
    "make_pair",
    "make_tuple",
    "get",
    "function",
    "bind",
    "hash",
    // Thread
    "thread",
    "mutex",
    "recursive_mutex",
    "condition_variable",
    "async",
    "future",
    "promise",
    "packaged_task",
    "scoped_lock",
    "jthread",
    // Memory
    "allocator",
    "new",
    "delete",
    // Type traits
    "is_integral",
    "is_floating_point",
    "is_pointer",
    "is_reference",
    "is_const",
    "is_array",
    "is_function",
    "is_class",
    "is_enum",
    "is_same",
    "is_base_of",
    "is_convertible",
    "is_constructible",
    "enable_if",
    "conditional",
    "decay",
    "remove_reference",
    "remove_const",
    "add_pointer",
    "add_reference",
    "add_const",
    "integral_constant",
    "true_type",
    "false_type",
    // Constants
    "size_t",
    "ptrdiff_t",
    "nullptr_t",
    "nullopt",
    "npos",
];

impl BuiltinFilter {
    /// Returns `true` if the name is a known built-in for the given language
    /// and should be excluded from resolution.
    pub fn is_builtin(name: &str, lang: Language) -> bool {
        match lang {
            Language::TypeScript | Language::JavaScript | Language::ArkTS => {
                TS_JS_BUILTINS.contains(&name)
            }
            Language::Python => PYTHON_BUILTINS.contains(&name),
            Language::Java => JAVA_BUILTINS.contains(&name),
            Language::C => C_BUILTINS.contains(&name),
            Language::Cpp => CPP_BUILTINS.contains(&name),
            _ => false,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_ts_js_builtins() {
        assert!(BuiltinFilter::is_builtin("console", Language::TypeScript));
        assert!(BuiltinFilter::is_builtin("Promise", Language::JavaScript));
        assert!(BuiltinFilter::is_builtin("window", Language::ArkTS));
        assert!(!BuiltinFilter::is_builtin(
            "myFunction",
            Language::TypeScript
        ));
    }

    #[test]
    fn test_python_builtins() {
        assert!(BuiltinFilter::is_builtin("print", Language::Python));
        assert!(BuiltinFilter::is_builtin("len", Language::Python));
        assert!(!BuiltinFilter::is_builtin("numpy", Language::Python));
    }

    #[test]
    fn test_java_builtins() {
        assert!(BuiltinFilter::is_builtin("String", Language::Java));
        assert!(BuiltinFilter::is_builtin("System", Language::Java));
        assert!(BuiltinFilter::is_builtin("Object", Language::Java));
        assert!(BuiltinFilter::is_builtin("null", Language::Java));
        assert!(BuiltinFilter::is_builtin("ArrayList", Language::Java));
        assert!(BuiltinFilter::is_builtin("HashMap", Language::Java));
        assert!(BuiltinFilter::is_builtin("IOException", Language::Java));
        assert!(!BuiltinFilter::is_builtin("MyService", Language::Java));
    }

    #[test]
    fn test_c_builtins() {
        assert!(BuiltinFilter::is_builtin("printf", Language::C));
        assert!(BuiltinFilter::is_builtin("malloc", Language::C));
        assert!(BuiltinFilter::is_builtin("size_t", Language::C));
        assert!(BuiltinFilter::is_builtin("NULL", Language::C));
        assert!(BuiltinFilter::is_builtin("free", Language::C));
        assert!(!BuiltinFilter::is_builtin("my_function", Language::C));
    }

    #[test]
    fn test_cpp_builtins() {
        assert!(BuiltinFilter::is_builtin("cout", Language::Cpp));
        assert!(BuiltinFilter::is_builtin("std", Language::Cpp));
        assert!(BuiltinFilter::is_builtin("vector", Language::Cpp));
        assert!(BuiltinFilter::is_builtin("string", Language::Cpp));
        assert!(BuiltinFilter::is_builtin("make_unique", Language::Cpp));
        assert!(BuiltinFilter::is_builtin("nullptr", Language::Cpp));
        assert!(!BuiltinFilter::is_builtin("MyClass", Language::Cpp));
    }
}
