[workspace]
members = [
    "crates/atlas-engine",
    "crates/atlas-engine/crates/*",
    "crates/atlas-engine/crates/domain_rules",
    "crates/atlas-cli",
    "crates/atlas-mcp",
]
resolver = "2"

[workspace.package]
version = "1.6.0"
edition = "2024"
license = "MIT"

[profile.release]
strip = true
lto = "fat"
opt-level = 3
codegen-units = 1
